// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBymcinO0oeKGuDWAhlfidJfgf9U5f4WXU',
    appId: '1:179735631850:web:98a7cea98ccd40fa738493',
    messagingSenderId: '179735631850',
    projectId: 'flutter-firebase-e94ed',
    authDomain: 'flutter-firebase-e94ed.firebaseapp.com',
    storageBucket: 'flutter-firebase-e94ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfcVFegli68auZHpwYtAHP2iuCNjXx3lM',
    appId: '1:179735631850:android:dab150e8e762b107738493',
    messagingSenderId: '179735631850',
    projectId: 'flutter-firebase-e94ed',
    storageBucket: 'flutter-firebase-e94ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBy9phz87ER3pTBBE1qkQbdhSh1lQGED0',
    appId: '1:179735631850:ios:815127ef70aaed43738493',
    messagingSenderId: '179735631850',
    projectId: 'flutter-firebase-e94ed',
    storageBucket: 'flutter-firebase-e94ed.appspot.com',
    iosClientId: '179735631850-mpos3ogbc0lpnop3hu3k4n6vr7lvti9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.mehmetkurt.firebase98',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBy9phz87ER3pTBBE1qkQbdhSh1lQGED0',
    appId: '1:179735631850:ios:815127ef70aaed43738493',
    messagingSenderId: '179735631850',
    projectId: 'flutter-firebase-e94ed',
    storageBucket: 'flutter-firebase-e94ed.appspot.com',
    iosClientId: '179735631850-mpos3ogbc0lpnop3hu3k4n6vr7lvti9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.mehmetkurt.firebase98',
  );
}
